networks:
  cv-ideal-network:
    name: cv-ideal-network
    driver: bridge


services:
  backend:
    container_name: cv_api
    restart: always
    env_file: .env
    build: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - cv-ideal-network
    command: yarn start
    depends_on:
      - database
    volumes:
      - ./:/usr/src
      - ./node_modules:/usr/src/node_modules

  database:
    container_name: cv_database
    image: postgres
    restart: always
    env_file:
      - .env 
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}
    networks:
      - cv-ideal-network
    environment:
      POSTGRES_DB: ${DB_DATABASE} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}

  
  database_test:
    container_name: cv_database_test
    image: postgres
    restart: always
    env_file:
      - .env 
    ports:
      - ${DB_TEST_EXTERNAL_PORT}:${DB_TEST_PORT}
    networks:
      - cv-ideal-network
    environment:
      POSTGRES_DB: ${DB_TEST_DATABASE} 
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
      POSTGRES_USER: ${DB_TEST_USERNAME}

    
